### ISSUE TITLE
Extension missing

### ISSUE THREAD

**Issue by Fernsehstuhl** [beanieboi/moneymoney-estateguru#12]
Hi!

Since about 2 weeks came an error when retrieving. I have now copied the new Luna file - now the extension is not displayed in the menu at all.

What can be the reason for this?

to use unsigned extension uncheck “verify digital signatures of extensions” at the bottom
--> Unfortunately I can not find...

 Ignoring 'estateguru.lua' because signature verification failed.

**Comment by beanieboi** [comment]
sorry, I can't provide support for MoneyMoney
