### ISSUE TITLE
Passwords with special characters not supported

### ISSUE THREAD

**Issue by bensch777** [beanieboi/moneymoney-estateguru#2]
If you have a password with special characters liker *#% the extension is not working. Maybe there is an issue with the url encoding?

After changing the password to a password without special characters it was working as expected.

**Comment by lr1980** [comment]
try this edit: 
https://github.com/lr1980/moneymoney-estateguru/tree/3d0386eda38b9070bc768509dda76466328b56fb

**Comment by bensch777** [comment]
Works. thx

**Comment by lr1980** [comment]
#3
