### ISSUE TITLE
Stopped working for German account

### ISSUE THREAD

**Issue by SirSurfalot** [beanieboi/moneymoney-estateguru#6]
Estateguru must have changed something. The extension stopped working today. Account language in estateguru is English, device has German Mac OS.

Excerpt from protocol:
...
16:01:32  1> Received:  <!doctype html> <html lang="en" class="no-js"> <head>     <title>         Kontoübersicht     </title>...
...
1> estateguru.lua: expected number for 'securities.purchasePrice', securities name `Account Summary'
1> Konnte den Wertpapierbestand nicht abfragen.
1> Received 0 portfolio items.

**Comment by SirSurfalot** [comment]
Estateguru seems to send German data now.
It looks like the extension expects "Account Summary" when "Kontoübersicht" has been parsed.

**Comment by SirSurfalot** [comment]
Excerpt from protocol:
  1> Sending: GET https://estateguru.co/portal/portfolio/overview

Command in script, however, is
content = HTML(connection:get("https://estateguru.co/portal/portfolio/overview?lang=en"))

It seems like '?lang=en' is not passed on. Therefore German is passed back, therefore parsing fails.

**Comment by beanieboi** [comment]
I'm sorry for this. I don't use estateguru anymore and deleted my account. I'm unable to fix this but I will accept a PR

**Comment by SirSurfalot** [comment]
Issue is resolved. Updated signed LUA is available at https://moneymoney-app.com/extensions and verified working.
Thanks go to MRH applications.
