### ISSUE TITLE
securities PurchasePrice Error

### ISSUE THREAD

**Issue by oyyyam** [beanieboi/moneymoney-estateguru#7]
Hi,
I just set up my EG Account in MoneyMoney but I keep getting this Error:

<img width="751" alt="Bildschirmfoto 2020-10-22 um 12 19 15" src="https://user-images.githubusercontent.com/73284772/96860088-a014cb80-1462-11eb-85b8-7af46a04cd61.png">

**Comment by SirSurfalot** [comment]
I have the same issue.

Estateguru seems to send German data now.
It looks like the extension expects "Account Summary" when "Kontoübersicht" has been parsed.

**Comment by beanieboi** [comment]
I'm sorry for this. I don't use estateguru anymore and deleted my account. I'm unable to fix this but I will accept a PR

**Comment by SirSurfalot** [comment]
Issue is resolved. Updated signed LUA is available at https://moneymoney-app.com/extensions and verified working.
Thanks go to MRH applications.
